### ISSUE TITLE
Range of PC (Probability of Conectivity)

### ISSUE THREAD

**Issue by andreregolin** [connectscape/Makurhini#3]
Dear Dr. Oscar and Dr. Camilo,

I have noticed that the overall PC does not range from 0-1 as expected according to the Conefor manual. What am I doing wrong?

To exemplify, I used the example of the package. Please see below. 

> data("vegetation_patches", package = "Makurhini")
> nrow(vegetation_patches) # Number of patches
[1] 142
>
> PC <- MK_dPCIIC(nodes = vegetation_patches, attribute = NULL,
+                  distance = list(type = "centroid"),
+                  metric = "PC",
+                  overall=T,
+                  onlyoverall = T,
+                  distance_thresholds = 10000) #10 km
> head(PC)
    Index        Value
1:  PCnum 2.024674e+11
2: EC(PC) 4.499638e+05
>
> PC$Value[2]
[1] 449963.8

Best regards!

**Comment by connectscape** [comment]
Dear Dr. André Luis Regolin,

An apology for the delay in reply. Yes, the metric is EC (PC) or Equivalent Connected (0-sum of node attributes) which when is estimated using areas is called Equivalent Connected Area, ECA. The PC metric (0-1) appears as a result when additionally using the LA or Maximum landscape attribute argument. Example:

library(Makurhini)
data("vegetation_patches", package = "Makurhini")
nrow(vegetation_patches) # Number of patches

# If we use the area of the state of Chiapas where the vegetation patches are located
# 7.3311e+10 m2

#Two distance threshold,
PC <- MK_dPCIIC(nodes = vegetation_patches, attribute = NULL,
                area_unit = "m2",
                distance = list(type = "centroid"),
                LA = 7.3311e+10,
                overall = T,
                onlyoverall = T,
                metric = "PC", distance_thresholds = 10000) #1:10 km

#   Index        Value
#1:  PCnum 2.024576e+19
#2: EC(PC) 4.499529e+09
#3:     PC 3.767001e-03

Best regarts!
